# Generated by Django 4.2.7 on 2023-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_phone', models.CharField(max_length=13)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
